const mongoose = require('mongoose');

const MediaSchema = new mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  name: String,
  date: String,
  type: String,
  whatsapp: String,
  source: String,
  email: String,
  template_name: String,
  photoId: mongoose.Schema.Types.ObjectId,
  videoId: mongoose.Schema.Types.ObjectId,
  posterId: mongoose.Schema.Types.ObjectId,
  video1Id: mongoose.Schema.Types.ObjectId,
  video2Id: mongoose.Schema.Types.ObjectId,
  posterVideoId: mongoose.Schema.Types.ObjectId,
  mergedVideoId: mongoose.Schema.Types.ObjectId,
  gifId: mongoose.Schema.Types.ObjectId,
  audioId: mongoose.Schema.Types.ObjectId,
  templateId: mongoose.Schema.Types.ObjectId,
  whatsappstatus: String,
  qrCode: { type: String },
  adminid: { type: String, default: "" },
  branchName: { type: String, default: "" },
  whatsappsharecount: { type: Number, default: 0 },
  facebooksharecount: { type: Number, default: 0 },
  twittersharecount: { type: Number, default: 0 },
  instagramsharecount: { type: Number, default: 0 },
  downloadcount: { type: Number, default: 0 },
  urlclickcount: { type: Number, default: 0 },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model('medias', MediaSchema);
